//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtaghMan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_tbl
    {
        public int EQUIPMENT_ID { get; set; }
        public string EQUIPMENT_NAME { get; set; }
        public int EQUIPMENT_TYPE { get; set; }
        public string EQUIPMENT_PIC { get; set; }
        public int EQUIPMENT_STORAGE { get; set; }
    
        public virtual Storages_tbl Storages_tbl { get; set; }
    }
}
