//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtaghMan.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtaghMan_DBEntities : DbContext
    {
        public OtaghMan_DBEntities()
            : base("name=OtaghMan_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Equipment_tbl> Equipment_tbl { get; set; }
        public virtual DbSet<Rooms_tbl> Rooms_tbl { get; set; }
        public virtual DbSet<Storages_tbl> Storages_tbl { get; set; }
        public virtual DbSet<Users_tbl> Users_tbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
