//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtaghMan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rooms_tbl()
        {
            this.Storages_tbl = new HashSet<Storages_tbl>();
        }
    
        public int ROOM_ID { get; set; }
        public string ROOM_NAME { get; set; }
        public string ROOM_PIC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storages_tbl> Storages_tbl { get; set; }
    }
}
