//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtaghMan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storages_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storages_tbl()
        {
            this.Equipment_tbl = new HashSet<Equipment_tbl>();
        }
    
        public int STORAGE_ID { get; set; }
        public string STORAGE_NAME { get; set; }
        public string STORAGE_TYPE { get; set; }
        public int ROOM_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_tbl> Equipment_tbl { get; set; }
        public virtual Rooms_tbl Rooms_tbl { get; set; }
    }
}
